project:
  type: book
  output-dir: docs

book:
  title: "R for Bio Data Science"
  reader-mode: true
  page-navigation: true

  page-footer:
    left: |
      R for Bio Data Science
    right: |
      Full course description available at <a href="https://kurser.dtu.dk/course/22100">DTU Course Base</a>.
  
  cover-image: images/r4bds_logo_v2.png
  
  chapters:
    - index.qmd
    - prologue.qmd
    - getting_started.qmd
    
    - part: lab00.qmd
      chapters:
        - lab01.qmd
        - lab02.qmd
        - lab03.qmd
        - lab04.qmd
        - lab05.qmd
        - lab06.qmd
        - lab07.qmd
        - lab08.qmd
        - lab09.qmd
        - lab10.qmd
        
    - assignments.qmd
    - project_faq.qmd
    - exam.qmd
    - resources.qmd

format:
  html:
    theme: cosmo
    mainfont: avenir
    fontsize: 18px

editor: source

